item {
    id: 1
    name: 'RedLeftArrow'
}

item {
    id: 2
    name: 'RedRightArrow'
}

item {
    id: 3
    name: 'LeftArrow'
}

item {
    id: 4
    name: 'RightArrow'
}

item {
    id: 5
    name: 'Avatar'
}